Added fix for the yocto rebase build failure
Fixed below errors found during yocto rebase due to missing header
file algorithm.

    calculate.cpp:
        error: 'sort' is not a member of 'std'; did you mean 'qsort'?
        error: 'max_element' is not a member of 'std'; did you mean 'tuple_element'?
        error: 'min_element' is not a member of 'std'; did you mean 'tuple_element'?

Tested: Build verified with yocto rebase patches.

Change-Id: Ie6f920e20a8ddb4b953b246b0debc4be87fa2462
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>